/**
Project: Yield-Yeti apis 
version : v0.1
author : @badrik-github , @jimishio
desc : Schema for User.
*/


//Require Modules
var mongoose = require("mongoose");

//Password Encryption Modules
const { v4: uuidv4 } = require('uuid');

//Making Schema
const UserSchema = new mongoose.Schema({

    //name of user
    name: {
        type: String
    },

    //email of user
    email: {
        type: String,
        unique: true
    },

    //encrypted password of user
    encryptPassword: {
        type: String
    },

    //salt used to encrypt password (AutoGenerated)
    salt: {
        type: String,
        default: uuidv4()
    },

    //Google secret of 2FA
    googleSecret: {

    }

}, { timestamps: true })


//Exporting Schema
var Users = mongoose.model('Users', UserSchema);
module.exports = { Users }